# Target architecture of the UML kernel binary file. Valid values include:
# i386, ia64, ppc, and x86_64
SUBARCH?=x86_64

# Kernel release
# 3.0.75 introduced mm/memory.c change by Linus that breaks UML
# (at least up to .80)
KERNEL_RELEASE?=3.0.74

# URL of the kernel tarball, if required
KERNEL_SUFFIX=.tar.xz
KERNEL_URL=http://www.kernel.org/pub/linux/kernel/v3.x/linux-$(KERNEL_RELEASE)$(KERNEL_SUFFIX)
