# Target architecture of the UML kernel binary file. Valid values include:
# i386, ia64, ppc, and x86_64
SUBARCH?=i386

# Kernel release
KERNEL_RELEASE?=3.2.39

# URL of the kernel tarball, if required
KERNEL_SUFFIX=.tar.xz
KERNEL_URL=http://www.kernel.org/pub/linux/kernel/v3.x/linux-$(KERNEL_RELEASE)$(KERNEL_SUFFIX)
